dist: xenial
sudo: true

language: php
cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    # all supported PHP versions with lowest dependencies
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
# @TODO: uncomment when cassandra extension will support >= php7.2
#    - php: 7.2
#      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
#    - php: 7.3
#      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
#    - php: 7.4
#      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    # symfony LTS versions
    - php: 7.1
      env: SYMFONY_REQUIRE="3.4.*"
    - php: 7.1
      env: SYMFONY_REQUIRE="4.4.*"

before_install:
  # disable xdebug
  - phpenv config-rm xdebug.ini
  # install cassandra extension
  - wget http://downloads.datastax.com/cpp-driver/ubuntu/16.04/dependencies/libuv/v1.34.0/libuv1_1.34.0-1_amd64.deb
  - wget http://downloads.datastax.com/cpp-driver/ubuntu/16.04/dependencies/libuv/v1.34.0/libuv1-dev_1.34.0-1_amd64.deb
  - wget http://downloads.datastax.com/cpp-driver/ubuntu/16.04/cassandra/v2.15.0/cassandra-cpp-driver_2.15.0-1_amd64.deb
  - wget http://downloads.datastax.com/cpp-driver/ubuntu/16.04/cassandra/v2.15.0/cassandra-cpp-driver-dev_2.15.0-1_amd64.deb
  - sudo dpkg -i *.deb
  - pecl channel-update pecl.php.net
  - pecl install cassandra
  # setup composer dependencies
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - bin/coke
  - bin/atoum
