language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - SYMFONY_VERSION="~2.3.0"
  - SYMFONY_VERSION="~2.7.0"
  - SYMFONY_VERSION="~3.2.0"

branches:
  only:
    - master

before_install:
  # disable xdebug
  - phpenv config-rm xdebug.ini
  # PPA for libuv-dev
  - sudo apt-add-repository ppa:linuxjedi/ppa -y
  - sudo apt-get update
  - sudo apt-get install -y libssl-dev
  - cd /tmp && wget https://github.com/libuv/libuv/archive/v1.11.0.tar.gz && tar -xvzf v1.11.0.tar.gz && cd libuv-1.11.0 && sh autogen.sh && ./configure && sudo make && sudo make install && sudo ldconfig
  - cd /tmp && git clone https://github.com/datastax/php-driver.git && cd php-driver && git checkout master && git submodule update --init
  - cd ext && ./install.sh && cd "$TRAVIS_BUILD_DIR"
  - echo "extension=cassandra.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

install:
  - composer install -n

before_script:
  - composer require --no-update --dev symfony/dependency-injection:${SYMFONY_VERSION} symfony/event-dispatcher:${SYMFONY_VERSION} symfony/config:${SYMFONY_VERSION} symfony/yaml:${SYMFONY_VERSION}
  - composer update --prefer-dist --no-interaction

script:
  - bin/atoum

