language: php

php:
  - 5.5

branches:
  only:
    - master

before_install:
  # PPA for libuv-dev
  - sudo apt-add-repository ppa:linuxjedi/ppa -y
  - sudo apt-get update
  - sudo apt-get install -y libuv-dev libssl-dev
  - cd /tmp && git clone https://github.com/datastax/php-driver.git && cd php-driver && git submodule update --init
  - cd ext && ./install.sh && cd "$TRAVIS_BUILD_DIR"
  - echo "extension=cassandra.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

install:
  - composer install -n --dev

script:
  - bin/atoum

