language: php

php:
  - 5.5
  - 7.0

env:
  - SYMFONY_VERSION="~2.3.0"
  - SYMFONY_VERSION="~2.7.0"
  - SYMFONY_VERSION="~3.0.0"

branches:
  only:
    - master

before_install:
  # disable xdebug
  - phpenv config-rm xdebug.ini
  # PPA for libuv-dev
  - sudo apt-add-repository ppa:linuxjedi/ppa -y
  - sudo apt-get update
  - sudo apt-get install -y libuv-dev libssl-dev
  - cd /tmp && git clone https://github.com/datastax/php-driver.git && cd php-driver && git submodule update --init
  - cd ext && ./install.sh && cd "$TRAVIS_BUILD_DIR"
  - echo "extension=cassandra.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

install:
  - composer install -n

before_script:
  - composer require --no-update --dev symfony/dependency-injection:${SYMFONY_VERSION} symfony/event-dispatcher:${SYMFONY_VERSION} symfony/config:${SYMFONY_VERSION} symfony/yaml:${SYMFONY_VERSION}
  - composer update --prefer-dist --no-interaction

script:
  - bin/atoum

